---
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run yamllint
        run: uv run yamllint defaults/ handlers/ meta/ tasks/ molecule/

      - name: Run ansible-lint
        run: uv run ansible-lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run Molecule test
        run: uv run molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_NO_LOG: false

  release-check:
    name: Release Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for version bump
        run: |
          if git diff --name-only origin/main...HEAD | grep -q "meta/main.yml"; then
            echo "✅ meta/main.yml was modified - version may have been updated"
          else
            echo "⚠️ Consider updating the version in meta/main.yml for this release"
          fi